baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my portfolio
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Ankita Portfolio" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ankita."
    subtitle: "Tech Enthusiast and Problem Solver: Showcasing a Journey in Technical Excellence."
    content: "From Algorithms to Applications: A Technical Odyssey in the Digital Landscape."
    image: "\images\AC.jpg"
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/anki9905
       # - icon: fab fa-twitter
        #  url: https://example.com
      #customIcons:
       # - icon: /fav.png
         # url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: ""C:\Users\ANKITA\website-template\images\AC.jpg""
    content: |-
      Passionate about developing innovative software solutions and eager to solve complex problems using multiple methods.Quick Learner with Continuous Growth. 
    skills:
      enable: true
      title: "Here are a few things which I know:"
      items:
        - "DS/ ML/AL : Machine Learning Algorithms, ANN, CNN, NLP, Data Preprocessing."
        - "Python packages and Frameworks : NumPy,Pandas,Matplotlib,Seaborn, Scikit-Learn,Tensorflow,Keras,SciPy,Beautiful Soup."
        - "Programming & Database Language : Python3, MySQL,MongoDB, Postgresql"
        - "Mlops Tools : DVC, git actions(CI/CD) ,Airflow."
        - "Web Development : HTML, CSS, Javascript, PHP, Bootstrap, React, Django,Fast API, Flask, Web scraping"
        - "IDEs : Jupyter Notebook, VS Code, PyCharm, Google Colab."
        - "Visualization Tool : Excel, Power BI, Looker, Tableau."
        - "Cloud Based Deployment and Containers : AWS, Git, Docker, Code Pipeline."


  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Machine Learning Intern"
        company: "SPK-MAK Technologies"
        date: "June 2023 - Sept 2023"
        content: "During this internship, I was able to direct predictive modeling to forecast liability customer's likelihood of purchasing personal loans. Applied logistic regression for accuracy improvement and orchestrated successful model deployment, showcasing strategic financial decision-making and technical proficiency."


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Computer Applications"
        school:
          name: "Birla Global University,Bhubaneswar"
        date: "2022 - 2024 "
        CGPA: "10"

      - title: "Master of Science"
        school:
          name: "Centurion University"
        date: "2020 - 2022"
        CGPA: "9.4"

      - title: "Bachelor of Science."
        school:
          name: "Fakir Mohan University"
        date: "2017 - 2020"
        CGPA: "8.36"

  # Projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Medicine Recommendation System.
        content: Built a dynamic System, integrating innovative recommendation algorithms and deploying a user-friendly API. Demonstrated technical prowess and strategic decision-making, personalization in healthcare informatics.
      - title: Detecting Credit Card Fraud.
        content: Led a pivotal initiative, employing advanced anomaly detection techniques. Engineered robust models, showcasing strategic decision-making and expertise in enhancing financial security.
      - title: Fake News detection Model.
        content: Developed a sophisticated Fake News Detection Model, implementing intricate algorithms for nuanced analysis. Leveraged expertise in natural language processing and machine learning, contributing to the ongoing battle against misinformation.Built a restful api and deployed to EC2 instance using docker and github actions.
      - title: Crop Potato Disease Detection.
        content: Directed the cutting-edge Crop Potato Disease Detection initiative, employing TensorFlow and OpenCV for computer vision. Implemented a Custom Convolutional Neural Networks (CNN) for intricate disease pattern recognition. Employed cloud-based storage solutions for efficient data management. Demonstrated advanced expertise in agrotech and deep learning, fostering sustainable agricultural practices.
      - title: Building a powerful Job Recommendation System.
        content: Steered the development of a potent System, leveraging advanced recommendation algorithms. Oversaw model deployment via an API, showcasing technical expertise & strategic decision-making in talent acquisition.
      - title: Research Paper Recommendation System & Subject Area Prediction.
        content: Directed the creation of an advanced Research Paper Recommendation System, employing state-of-the-art algorithms. Developed a model predicting subject areas, showcasing versatile expertise in academic research and predictive analytics.
      - title: Grammar and Spell Checker App with Python.
        content: Orchestrated the development of a sophisticated Grammar and Spell Checker App using Python. Applied cutting-edge algorithms for precise language analysis, showcasing expertise in natural language processing and advanced software engineering.

  # Certifications
  certification:
    enable: true
    # title: "Custom Name"
    items:
      - title: Introduction to Cloud Computing - IBM Certified
      - title: Introduction to DevOps from Coursera
      - title: Tools for Data Science from Coursera
      - title: Machine Minds - A Workshop on Machine Learning and Data Science
       
  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: ankitachoudhury9905@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
#    recentPosts:
#      path: "blogs"
#      count: 3
#      title: Recent Posts
#      enable: true
#      disableFeaturedImage: false
    socialNetworks:
      linkedin: https://www.linkedin.com/in/ankita9905/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
