baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Viyoni."
    subtitle: "Shaping healthy futures, one consultation at a time."
    content: "Melding medicine and marketing to create thriving healthcare solutions."
    image: /images/hero.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-twitter
          url: https://example.com
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am an MD with a passion for better healthcare solutions, currently honing my business acumen at 
      Duke's Fuqua school of business. As an aspiring consultant, I am eagerly exploring the fusion of medicine and management, poised to drive
      innovation and bring more empathy in healthcare. 
    skills:
      enable: true
      title: "Here are a few things which I know:"
      items:
        - "Patient care"
        - "Microsoft Excel"
        - "Medical research"
        - "Finance and Accouting"
        - "Statistics"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Medical intern"
        company: "MK Shah Medical college"
        date: "April 2022 - April 2023"
        content: "During this internship, I was able to apply theoretical knowledge from my medical studies in real-world clinical settings. Responsibilities included conducting patient histories and physical examinations, developing diagnostic plans, and managing patient cases under the supervision of experienced doctors. I also participated in regular ward rounds, surgical procedures, and multidisciplinary team meetings. This experience deepened my understanding of patient care and the intricacies of the healthcare system, which I am keen to leverage in my future career as a healthcare consultant."


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Management"
        school:
          name: "Fuqua school of business, Durham"
        date: "2023 - "

      - title: "MBBS"
        school:
          name: "M.K.Shah Medical college"
        date: "2017 - 2022"
        CGPA: "7.1"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Conducted a survey of 1400 households to evaluate how many women get cervical screenings done
        content: 552 women, belonging to age group 25 to 64.
      - title: Organized one on one counselling sessions.
        content: Created awareness among many women to undergo regular screenings to prevent HPV infection.
      - title: Trained 100 nursing students
        content: Taught them various aspects of healthcare including sample collection, intravenous admission of drugs.
      - title: Managed 10 teams responsible for daily house visits of Covid patients
        content: Oversaw daily vitals and symptoms of every patient brought to me by 10 teams and deciding if hospitalisation is imperative or not.

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: viyonithakkar3@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
#    recentPosts:
#      path: "blogs"
#      count: 3
#      title: Recent Posts
#      enable: true
#      disableFeaturedImage: false
    socialNetworks:
      linkedin: https://linkedin.cohttps://www.linkedin.com/in/dr-viyoni-thakkar-b59792248/?originalSubdomain=inm

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
